^SC029::Send "⋄"
^+SC029::Send "⌺"
^1::Send "¨"
^+1::Send "⌶"
^2::Send "¯"
^+2::Send "⍫"
^3::Send "<"
^+3::Send "⍒"
^4::Send "≤"
^+4::Send "⍋"
^´::Send "÷"
^+´::Send "⌹"
^5::Send "="
^+5::Send "⌽"
^6::Send "≥"
^+6::Send "⍉"
^7::Send ">"
^+7::Send "⊖"
^8::Send "≠"
^+8::Send "⍟"
^9::Send "∨"
^+9::Send "⍱"
^0::Send "∧"
^+0::Send "⍲"
^ß::Send "×"
^+ß::Send "{!}"
^q::Send "?"
^+q::Send "⍰"
^w::Send "⍵"
^+w::Send ""
^e::Send "∊"
^+e::Send "⍷"
^r::Send "⍴"
^+r::Send ""
^t::Send "~"
^+t::Send "⍨"
^z::Send "↑"
^+z::Send ""
^u::Send "↓"
^+u::Send ""
^i::Send "⍳"
^+i::Send "⍸"
^o::Send "○"
^+o::Send "⍥"
^p::Send "*"
^+p::Send "⍣"
^ü::Send "←"
^+ü::Send "⍞"
^+::Send "→"
^++::Send "⍬"
^a::Send "⍺"
^+a::Send ""
^s::Send "⌈"
^+s::Send ""
^d::Send "⌊"
^+d::Send ""
^f::Send "_"
^+f::Send "⍛"
^g::Send "∇"
^+g::Send "⍢"
^h::Send "∆"
^+h::Send ""
^j::Send "∘"
^+j::Send "⍤"
^k::Send "'"
^+k::Send "⌸"
^l::Send "⎕"
^+l::Send "⌷"
^ö::Send "⍎"
^+ö::Send "≡"
^ä::Send "⍕"
^+ä::Send "≢"
^<::Send "⊢"
^+<::Send "⊣"
^y::Send "⊂"
^+y::Send "⊆"
^x::Send "⊃"
^+x::Send "⊇"
^c::Send "∩"
^+c::Send ""
^v::Send "∪"
^+v::Send ""
^b::Send "⊥"
^+b::Send ""
^n::Send "⊤"
^+n::Send "¤"
^m::Send "|"
^+m::Send "∥"
^,::Send "⍝"
^+,::Send "⍪"
^.::Send "⍀"
^+.::Send "⍙"
^-::Send "⌿"
^+-::Send "⍠"

;#SuspendExempt
;LControl & Space::Suspend
;#SuspendExempt False

GroupAdd "Classic", "ahk_exe C:\Program Files (x86)\Dyalog\Dyalog APL 12.1 Classic\dyalog.exe"
GroupAdd "Classic", "ahk_exe C:\Program Files\Dyalog\Dyalog APL-64 17.1 Classic\dyalog.exe"

Check() {
  if WinActive("ahk_group Classic") {
    Suspend True
  } else {
    Suspend False
  }
}

SetTimer Check, 500
